#!bin/bash

kubectl apply -f monitoring-namespace.yml
kubectl apply -f prometeheus-config.yaml
kubectl apply -f prometeheus-roles.yaml
kubectl apply -f prometeheus-deployment.yaml
kubectl apply -f prometeheus-nodeservice.yaml
minikube service --namespace=monitoring prometheus
