--- 

- name: Create HAProxy Default Configuration File.
  template:
    src=default.j2
    dest="{{ haproxy_default_path }}""{{ haproxy_default_file }}"
    owner=root group=root mode=644
     
- name: Create HAProxy Conf File.
  template:
    src=haproxy.j2
    dest="{{ haproxy_conf_path }}""{{ haproxy_conf_file }}"
    owner=root group=root mode=644
  notify: haproxy-restart
  
- name: create scripts directory 
  file:
    path: "{{ scripts_default_path }}"
    state: directory
    mode: '0755'

- name: create ping script
  template:
    src=ping.j2
    dest="{{ scripts_default_path }}""{{ ping_script }}"
    owner=root group=root mode=644
    
- name: create restart server script
  template: 
    src=restart.j2
    dest="{{ scripts_default_path }}""{{ restart_script }}"
    owner=root group=root mode=644
    
- name: launch ping script
  script: /etc/script/ping.sh
